# Generated by Django 4.2.2 on 2023-07-25 05:50

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_remove_supervisor_user_ptr_delete_accountant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_id', models.CharField(max_length=11, unique=True, verbose_name='National ID')),
                ('supervisor_code', models.CharField(max_length=30, unique=True, verbose_name='Supervisor Code')),
                ('supervisor_license', models.ImageField(upload_to='supervisor/license/', verbose_name='License')),
                ('accept_place', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator], verbose_name='Accepted Place')),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
