# Generated by Django 4.2.2 on 2023-07-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
