# Generated by Django 4.2.2 on 2023-07-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accountant',
            field=models.BooleanField(default=False, verbose_name='Accountant'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_people',
            field=models.BooleanField(default=True, verbose_name='People'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_supervisor',
            field=models.BooleanField(default=False, verbose_name='Supervisor'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Accountant', 'Accountant'), ('People', 'People')], default='People', max_length=100, verbose_name='Type'),
        ),
    ]
