# Generated by Django 4.2.2 on 2023-07-24 06:43

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_accountant_user_is_people_user_is_supervisor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_id', models.CharField(max_length=11, verbose_name='National ID')),
                ('accountant_code', models.CharField(max_length=30, verbose_name='Accountant Code')),
                ('accountant_license', models.FileField(upload_to='supervisor/license/', verbose_name='License')),
                ('accept_place', models.IntegerField(validators=[django.core.validators.MinValueValidator], verbose_name='Accepted Place')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('national_id', models.CharField(max_length=11, verbose_name='National ID')),
                ('supervisor_code', models.CharField(max_length=30, verbose_name='Supervisor Code')),
                ('supervisor_license', models.FileField(upload_to='supervisor/license/', verbose_name='License')),
                ('accept_place', models.IntegerField(validators=[django.core.validators.MinValueValidator], verbose_name='Accepted Place')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
