# Generated by Django 4.2.2 on 2023-07-24 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountant_options_alter_supervisor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='accept_place',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator], verbose_name='Accepted Place'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='accept_place',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator], verbose_name='Accepted Place'),
        ),
    ]
