# Generated by Django 4.2.2 on 2023-07-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_accountant_accept_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='accountant_license',
            field=models.ImageField(upload_to='supervisor/license/', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_license',
            field=models.ImageField(upload_to='supervisor/license/', verbose_name='License'),
        ),
    ]
