# Generated by Django 4.2.2 on 2023-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountant',
            name='accountant_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Accountant Code'),
        ),
        migrations.AlterField(
            model_name='accountant',
            name='national_id',
            field=models.CharField(max_length=11, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='national_id',
            field=models.CharField(max_length=11, unique=True, verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='supervisor_code',
            field=models.CharField(max_length=30, unique=True, verbose_name='Supervisor Code'),
        ),
    ]
