# Generated by Django 4.2.2 on 2023-08-02 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0002_paymentmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmark',
            name='price',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
    ]
