# Generated by Django 4.2.2 on 2023-08-02 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_alter_acceptedplace_created'),
        ('accountants', '0003_alter_paymentmark_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmark',
            name='accept_mark',
        ),
        migrations.AddField(
            model_name='paymentmark',
            name='accept_mark',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='marks.acceptedplace', verbose_name='Mark'),
            preserve_default=False,
        ),
    ]
