# Generated by Django 4.2.2 on 2023-08-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0004_remove_paymentmark_accept_mark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentMark',
        ),
    ]
