# Generated by Django 4.2.2 on 2023-08-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0007_paymentacceptedmark_delete_paymentmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentAcceptedMark',
        ),
    ]
