# Generated by Django 4.2.2 on 2023-08-02 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountants', '0012_rename_paymentaccepted_paymentmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmark',
            options={'verbose_name': 'PaymentMark', 'verbose_name_plural': 'PaymentMarks'},
        ),
        migrations.AddField(
            model_name='paymentmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmark',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
