# Generated by Django 4.2.2 on 2023-07-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placepoints',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
    ]
