# Generated by Django 4.2.2 on 2023-07-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisors', '0001_initial'),
        ('marks', '0002_alter_placepoints_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('level', models.CharField(choices=[('3', 'Hard'), ('2', 'Normal'), ('1', 'Easy')], default='2', verbose_name='Level')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='marks.placepoints', verbose_name='Mark')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup', to='supervisors.supervisor', verbose_name='Supervisor')),
            ],
        ),
    ]
