# Generated by Django 4.2.2 on 2023-07-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_acceptedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptedplace',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid or Unpaid'),
        ),
    ]
