# Generated by Django 4.2.2 on 2023-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_acceptedplace_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedplace',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
