# Generated by Django 4.2.2 on 2023-08-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_acceptedplace_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='placepoints',
            name='accept',
            field=models.IntegerField(default=0, verbose_name='accepted'),
        ),
        migrations.AddField(
            model_name='placepoints',
            name='failed',
            field=models.IntegerField(default=0, verbose_name='failed'),
        ),
    ]
