# Generated by Django 4.2.2 on 2023-08-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_placepoints_accept_placepoints_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedplace',
            name='action',
            field=models.CharField(choices=[('1', 'Accepted'), ('2', 'Failed')], default='1', max_length=3, verbose_name='accept or failed'),
        ),
    ]
