# Generated by Django 4.2.2 on 2023-08-02 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0008_alter_acceptedplace_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placepoints',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='placepoints',
            name='failed',
        ),
    ]
