# Generated by Django 4.2.2 on 2023-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_remove_placepoints_accept_remove_placepoints_failed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedplace',
            name='created',
            field=models.DateTimeField(verbose_name='Created'),
        ),
    ]
