# Generated by Django 4.2.2 on 2023-08-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_alter_acceptedplace_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedplace',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
